import React,{useEffect,useRef,useState}from'react';
import api from '../utils/api';
import {directUpload} from '../utils/directUpload';

export default function Dashboard(){
 const input=useRef(); const [folders,setFolders]=useState([]),[files,setFiles]=useState([]),[folder,setFolder]=useState(null),[query,setQuery]=useState(''),[results,setResults]=useState(null),[sort,setSort]=useState('newest'),[queue,setQueue]=useState([]),[preview,setPreview]=useState(null),[share,setShare]=useState(null),[error,setError]=useState('');
 const load=async(id=null)=>{try{const r=await api.get(id?'/folders/'+id+'/':'/folders/');setFolders(r.data.subfolders||[]);setFiles(r.data.files||[]);setFolder(r.data.current_folder||null)}catch{setError('Unable to load drive.')}};
 useEffect(()=>{load()},[]);
 useEffect(()=>{const t=setTimeout(async()=>{if(!query.trim())return setResults(null);try{setResults((await api.get('/files/search/',{params:{q:query}})).data)}catch{}},300);return()=>clearTimeout(t)},[query]);
 const ordered=[...(results?results.files:files)].sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='size'?b.size-a.size:sort==='oldest'?new Date(a.uploaded_at)-new Date(b.uploaded_at):new Date(b.uploaded_at)-new Date(a.uploaded_at));
 const upload=async(list)=>{const jobs=Array.from(list).map(f=>({file:f,progress:0,status:'queued'}));setQueue(q=>[...q,...jobs]);for(const job of jobs){setQueue(q=>q.map(x=>x===job?{...x,status:'uploading'}:x));try{await directUpload(job.file,folder?.id||null,p=>setQueue(q=>q.map(x=>x.file===job.file?{...x,progress:p}:x)));setQueue(q=>q.map(x=>x.file===job.file?{...x,progress:100,status:'done'}:x));await load(folder?.id)}catch{setQueue(q=>q.map(x=>x.file===job.file?{...x,status:'failed'}:x))}}};
 const previewFile=async f=>{try{const r=await api.get('/files/'+f.id+'/download/');setPreview({...f,url:r.data.url})}catch{setError('Preview unavailable')}};
 const makeShare=async f=>{try{setShare((await api.post('/files/'+f.id+'/share/',{})).data)}catch{setError('Could not create share link')}};
 const remove=async f=>{if(confirm('Move this file to Trash?')){await api.delete('/files/'+f.id+'/');load(folder?.id)}};
 return <main className="flex-1 bg-gray-950 text-white p-5 md:p-8"><div className="max-w-7xl mx-auto">
 <div className="flex flex-wrap gap-3 justify-between items-center"><div><h1 className="text-3xl font-black">{folder?.name||'My Drive'}</h1><p className="text-gray-500">Your S3, simplified.</p></div><div className="flex gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="🔍 Search files & folders" className="rounded-xl bg-gray-900 border border-gray-700 px-4 py-2"/><select value={sort} onChange={e=>setSort(e.target.value)} className="bg-gray-900 border border-gray-700 rounded-xl px-3"><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="name">Name A-Z</option><option value="size">Largest</option></select><button onClick={()=>input.current.click()} className="rounded-xl bg-purple-400 text-black font-bold px-4">Upload</button><input ref={input} type="file" multiple hidden onChange={e=>upload(e.target.files)}/></div></div>
 {error&&<p className="mt-4 text-red-300">{error}</p>}
 {queue.length>0&&<section className="mt-5 rounded-xl border border-gray-800 p-4"><b>Upload queue</b>{queue.map((x,i)=><div key={i} className="mt-2"><div className="flex justify-between text-sm"><span>{x.file.name}</span><span>{x.status} {x.progress}%</span></div><div className="h-2 bg-gray-800 rounded"><div className="h-2 bg-purple-400 rounded" style={{width:x.progress+'%'}}/></div></div>)}</section>}
 <section className="mt-8"><h2 className="text-sm uppercase text-gray-500 font-bold mb-3">Folders</h2><div className="grid sm:grid-cols-3 lg:grid-cols-5 gap-3">{(results?results.folders:folders).map(x=><button key={x.id} onClick={()=>load(x.id)} className="text-left p-4 rounded-xl bg-gray-900 border border-gray-800">📁 {x.name}</button>)}</div></section>
 <section className="mt-8"><h2 className="text-sm uppercase text-gray-500 font-bold mb-3">Files</h2><div className="divide-y divide-gray-800 rounded-xl border border-gray-800">{ordered.map(f=><div key={f.id} className="p-4 flex justify-between gap-3"><button onClick={()=>previewFile(f)} className="text-left font-semibold truncate">{f.name}<span className="block text-xs text-gray-500">{Math.round((f.size||0)/1024)} KB</span></button><div className="flex gap-2"><button onClick={()=>previewFile(f)} className="text-sm">Preview</button><button onClick={()=>makeShare(f)} className="text-sm">Share</button><button onClick={()=>remove(f)} className="text-sm text-red-300">Delete</button></div></div>)}</div></section>
 {preview&&<div className="fixed inset-0 bg-black/80 z-50 p-6 flex items-center justify-center"><div className="max-w-5xl max-h-full bg-gray-900 p-4 rounded-xl"><div className="flex justify-between mb-3"><b>{preview.name}</b><button onClick={()=>setPreview(null)}>✕</button></div>{/\.pdf$/i.test(preview.name)?<iframe title="preview" src={preview.url} className="w-[80vw] h-[75vh]"/>:/\.(png|jpg|jpeg|gif|webp)$/i.test(preview.name)?<img src={preview.url} className="max-w-[80vw] max-h-[75vh]"/>:<a href={preview.url} target="_blank" className="text-purple-300">Open file</a>}</div></div>}
 {share&&<div className="fixed inset-0 bg-black/80 z-50 flex items-center justify-center"><div className="bg-gray-900 p-6 rounded-xl"><h2 className="font-bold">Share link created</h2><input readOnly value={share.url} className="mt-3 w-80 bg-gray-800 p-2"/><div className="mt-3 flex gap-2"><button onClick={()=>navigator.clipboard.writeText(share.url)}>Copy</button><button onClick={()=>setShare(null)}>Close</button></div></div></div>}
 </div></main>
}